language: python
python:
- 3.6
services:
- docker
before_install:
- docker-compose up -d
- sleep 5
- export MARIADB_IP=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mariadb`
install:
- pip install -r tests/requirements.txt
script:
- pytest
