version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=emmental
      - MYSQL_USER=databaseuser
      - MYSQL_PASSWORD=securedatabasepassword
    volumes:
      - ./config/mariadb/emmental.sql:/docker-entrypoint-initdb.d/emmental.sql
    ports:
      - '3306'
    networks:
      emmental_network:
        ipv4_address: 10.0.0.10
  flask_web:
    build: ./config/flask/web/
    command: python -m flask run --host=flask_web
    container_name: flask_web
    environment:
      - MARIADB_IP=10.0.0.10
      - MARIADB_DATABASE=emmental
      - MARIADB_USER=databaseuser
      - MARIADB_PASSWORD=securedatabasepassword
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./src/:/srv/flask_web/
    working_dir: /srv/flask_web/
    ports:
      - '5000'
    depends_on:
      - mariadb
    networks:
      emmental_network:
        ipv4_address: 10.0.0.20
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./config/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '3000' # Only accessible on internal network
    depends_on:
      - flask_web
    networks:
      emmental_network:
        ipv4_address: 10.0.0.30
networks:
  emmental_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
