version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=emmental
      - MYSQL_USER=databaseuser
      - MYSQL_PASSWORD=securedatabasepassword
    volumes:
      - ./config/mariadb/emmental_database.sql:/docker-entrypoint-initdb.d/emmental_database.sql
    ports:
      - '3306'
    networks:
      emmental_network:
        ipv4_address: 10.0.0.10
  flask_web_app:
    build: ./config/webserver/
    command: python -m flask run --host=flask_web_app
    container_name: flask_web_app
    environment:
      - MARIADB_IP=10.0.0.10
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./config/webserver/emmental_flask/:/srv/emmental_flask/
    working_dir: /srv/emmental_flask/
    ports:
      - '5000'
    depends_on:
      - mariadb
    networks:
      emmental_network:
        ipv4_address: 10.0.0.20
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./config/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
    - flask_web_app
    networks:
      emmental_network:
        ipv4_address: 10.0.0.30
networks:
  emmental_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
